# Generated by Django 4.1.7 on 2023-04-18 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience', models.CharField(max_length=60)),
                ('Salary', models.FloatField()),
                ('Location', models.CharField(max_length=30)),
                ('Role', models.CharField(max_length=30)),
                ('Industry_Type', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Employment_Type', models.CharField(max_length=30)),
                ('Education', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=300)),
                ('Date_Of_Post', models.DateTimeField(default=None, null=True)),
                ('Time_Of_Post', models.TimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'Candidate_Listing',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('College_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'College',
            },
        ),
        migrations.CreateModel(
            name='Course_Dtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Course_Dtel',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Designation_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Designation_Type',
            },
        ),
        migrations.CreateModel(
            name='Education_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Education_Cat',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(default=None, null=True, upload_to='static/images/')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Industry_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Industry_Type',
            },
        ),
        migrations.CreateModel(
            name='JobCkrPrsnl_dtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('MOB', models.IntegerField()),
                ('Email', models.CharField(max_length=30)),
                ('Resume', models.FileField(default=None, null=True, upload_to='Resume/')),
                ('Experience', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('DOB', models.DateField(default=None, null=True)),
                ('Address', models.CharField(max_length=30)),
                ('Hometown', models.CharField(max_length=20)),
                ('Resume_Headline', models.CharField(max_length=200)),
                ('Photo', models.ImageField(default=None, null=True, upload_to='ProfilePhotos/')),
                ('Available_to_Join', models.CharField(default=None, max_length=60, null=True)),
            ],
            options={
                'db_table': 'JobCkrPrsnl_Dtel',
            },
        ),
        migrations.CreateModel(
            name='Joining_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATJ', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Joining_Availability',
            },
        ),
        migrations.CreateModel(
            name='Month_Years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'Month_Years',
            },
        ),
        migrations.CreateModel(
            name='Rec_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=50)),
                ('MOB', models.IntegerField()),
                ('Company_Name', models.CharField(max_length=60)),
                ('Designation', models.CharField(max_length=30)),
                ('Manpower', models.IntegerField(default=None, null=True)),
                ('Com_Description', models.CharField(max_length=200)),
                ('Logo', models.ImageField(default=None, null=True, upload_to='CompanyLogos/')),
                ('Photo', models.ImageField(default=None, null=True, upload_to='Companies_Photos/')),
            ],
            options={
                'db_table': 'Rec_Profile',
            },
        ),
        migrations.CreateModel(
            name='Skills_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skills', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Skills_Type',
            },
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Software', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Softwares',
            },
        ),
        migrations.CreateModel(
            name='States_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Category', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'States_Cat',
            },
        ),
        migrations.CreateModel(
            name='Project_Dtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=40)),
                ('Client', models.CharField(max_length=30)),
                ('Project_Status', models.CharField(max_length=20)),
                ('Project_Description', models.CharField(max_length=30)),
                ('JobCkrBELONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobckrprsnl_dtel')),
            ],
            options={
                'db_table': 'Project_Dtel',
            },
        ),
        migrations.CreateModel(
            name='JobCkrPrfessional_dtel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Industry', models.CharField(max_length=30)),
                ('Department', models.CharField(max_length=30)),
                ('Role_Category', models.CharField(max_length=30)),
                ('Job_Role', models.CharField(max_length=30)),
                ('Dzird_Job_Typ', models.CharField(max_length=30)),
                ('Dzird_Emp_Typ', models.CharField(max_length=30)),
                ('Prfrd_Shift', models.CharField(max_length=30)),
                ('Expktd_Salary', models.FloatField()),
                ('JobCkrBELONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobckrprsnl_dtel')),
            ],
            options={
                'db_table': 'JobCkrPrfessional_dtel',
            },
        ),
        migrations.CreateModel(
            name='Job_Ckr_Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(max_length=20)),
                ('University', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=20)),
                ('Course_Duration_From', models.DateField(default=None, null=True)),
                ('Course_Duration_Till', models.DateField(default=None, null=True)),
                ('Grade', models.CharField(max_length=10)),
                ('JobCkrBELONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobckrprsnl_dtel')),
            ],
            options={
                'db_table': 'Job_Ckr_Education',
            },
        ),
        migrations.CreateModel(
            name='ITSkillsBelongToTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITSkill', models.CharField(max_length=60)),
                ('SkillBelong_ToJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.candidate_listing')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rec_profile')),
            ],
            options={
                'db_table': 'ITSkillsBelongToTable',
            },
        ),
        migrations.CreateModel(
            name='IT_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Software_Name', models.CharField(max_length=30)),
                ('Version', models.CharField(max_length=20)),
                ('Experience', models.CharField(max_length=30)),
                ('JobCkrBELONG', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobckrprsnl_dtel')),
            ],
            options={
                'db_table': 'IT_Skills',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=30)),
                ('State_Belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.states_cat')),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.AddField(
            model_name='candidate_listing',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rec_profile'),
        ),
        migrations.CreateModel(
            name='Candidate_Job_Applied_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CandidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.jobckrprsnl_dtel')),
                ('JobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.candidate_listing')),
            ],
            options={
                'db_table': 'Candidate_Job_Applied_Detail',
            },
        ),
    ]
