# Generated by Django 4.1.7 on 2023-04-18 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_job_applied_detail',
            name='DateandTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='jobckrprsnl_dtel',
            name='Salary',
            field=models.FloatField(default=None, null=True),
        ),
    ]
