# Generated by Django 4.1.7 on 2023-04-18 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_candidate_job_applied_detail_dateandtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans_ForRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanName', models.CharField(max_length=60)),
                ('MaxPost_Allowed', models.IntegerField()),
                ('Price', models.FloatField()),
            ],
            options={
                'db_table': 'Plans_ForRec',
            },
        ),
        migrations.CreateModel(
            name='Rec_PlansAssisment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Counter', models.IntegerField()),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.plans_forrec')),
            ],
            options={
                'db_table': 'Rec_PlansAssisment_Details',
            },
        ),
    ]
