# Generated by Django 4.1.7 on 2023-04-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_plans_forrec_rec_plansassisment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rec_PlansAssisment_Details',
        ),
    ]
