# Generated by Django 4.1.7 on 2023-04-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_rec_plansassisment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_PlansAssisment_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post_Counter', models.IntegerField()),
                ('Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.plans_forrec')),
                ('Rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rec_profile')),
            ],
            options={
                'db_table': 'Rec_PlansAssisment_Details',
            },
        ),
    ]
