# Generated by Django 4.1.7 on 2023-04-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_bankingtransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankingTransaction',
        ),
    ]
