# Generated by Django 4.1.7 on 2023-04-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_bankingtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=60)),
                ('CardNo', models.CharField(max_length=16)),
                ('CVV', models.CharField(max_length=6)),
                ('ExpiryDate', models.CharField(max_length=15)),
                ('Balance', models.FloatField()),
                ('Recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rec_profile')),
            ],
            options={
                'db_table': 'BankingTransaction',
            },
        ),
    ]
